version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-lambda-ruby"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8irslr0fp2e1"
s3_prefix = "sam-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"

